export const sampleText = `React is a popular JavaScript library used for building user interfaces. It allows developers to create reusable UI components and manage the state of complex applications efficiently. With its virtual DOM and declarative syntax, React makes development faster and more intuitive.

Progressive Web Apps (PWAs) are web applications that offer an experience similar to native apps. They work offline, load quickly, and can be installed on a device's home screen. PWAs use service workers, web manifests, and caching strategies to provide reliable performance.

Smart search functionality helps users find information quickly by highlighting results and offering autocomplete suggestions. Combined with animations and keyboard navigation, it creates a seamless and interactive experience for the end user.

Building such a system requires careful attention to performance, accessibility, and responsiveness. Developers should avoid unnecessary libraries and focus on clean, readable, and well-structured code to ensure maintainability and scalability of the application.`;

export const dictionary = [
  "react",
  "is",
  "a",
  "popular",
  "javascript",
  "library",
  "used",
  "for",
  "building",
  "user",
  "interfaces",
  "it",
  "allows",
  "developers",
  "to",
  "create",
  "reusable",
  "ui",
  "components",
  "and",
  "manage",
  "the",
  "state",
  "of",
  "complex",
  "applications",
  "efficiently",
  "with",
  "its",
  "virtual",
  "dom",
  "declarative",
  "syntax",
  "makes",
  "development",
  "faster",
  "more",
  "intuitive",

  "progressive",
  "web",
  "apps",
  "pwas",
  "are",
  "applications",
  "that",
  "offer",
  "an",
  "experience",
  "similar",
  "native",
  "they",
  "work",
  "offline",
  "load",
  "quickly",
  "can",
  "be",
  "installed",
  "on",
  "device",
  "home",
  "screen",
  "use",
  "service",
  "workers",
  "manifests",
  "caching",
  "strategies",
  "provide",
  "reliable",
  "performance",

  "smart",
  "search",
  "functionality",
  "helps",
  "find",
  "information",
  "highlighting",
  "results",
  "offering",
  "autocomplete",
  "suggestions",
  "combined",
  "animations",
  "keyboard",
  "navigation",
  "creates",
  "seamless",
  "interactive",
  "experience",

  "building",
  "such",
  "system",
  "requires",
  "careful",
  "attention",
  "performance",
  "accessibility",
  "responsiveness",
  "should",
  "avoid",
  "unnecessary",
  "libraries",
  "focus",
  "clean",
  "readable",
  "well",
  "structured",
  "code",
  "ensure",
  "maintainability",
  "scalability",
  "application",
];
